inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

plugins: rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'

Rails/SaveBang:
  Enabled: false
