version: 2.1

filter-not-main: &filter-not-main
  filters:
    branches:
      ignore:
        - main
        - /^hotfix\/.+/

filter-main: &filter-main
  filters:
    branches:
      only:
        - main
        - /^hotfix\/.+/

filter-release: &filter-release
  filters:
    tags:
      only: /^release-202[\d-]+/
    branches:
      ignore:
        - "/.*/"

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  ruby: circleci/ruby@2
  node: circleci/node@5
  slack: circleci/slack@4.3.0
  gh: circleci/github-cli@1.0
  tariff: trade-tariff/trade-tariff-ci-orb@0
  terraform: circleci/terraform@3.2.1
  github-cli: circleci/github-cli@2.7.0

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:1.9.8
    resource_class: small
    working_directory: "/tmp/terraform"
    environment:
      TF_INPUT: 0
      TF_IN_AUTOMATION: 1
  python-executor:
    docker:
      - image: circleci/python:latest
    environment:
      TERRAFORM_VERSION: 1.9.8

jobs:
  trigger-github-e2e-tests:
    docker:
      - image: cimg/base:stable
    parameters:
      test_url:
        type: string
    steps:
      - checkout
      - github-cli/install
      - run:
          name: Trigger GitHub Workflow and Monitor
          command: |
            gh workflow run e2e-tests.yml \
              -R trade-tariff/trade-tariff-tools \
              --ref main \
              -f test-url="<< parameters.test_url >>"

            sleep 5 # Give it a moment to register
            RUN_ID=$(gh run list \
              --repo trade-tariff/trade-tariff-tools \
              --workflow=e2e-tests.yml \
              --branch=main \
              --limit=1 \
              --json databaseId \
              -q '.[0].databaseId')

            echo "GitHub Workflow triggered with Run ID: $RUN_ID"
            echo "Checking status (will not block pipeline)..."

            END_TIME=$((SECONDS+100))
            while [ $SECONDS -lt $END_TIME ]; do
              STATUS=$(gh run view $RUN_ID \
                --repo trade-tariff/trade-tariff-tools \
                --json conclusion,status \
                -q '.status')

              CONCLUSION=$(gh run view $RUN_ID \
                --repo trade-tariff/trade-tariff-tools \
                --json conclusion,status \
                -q '.conclusion')

              echo "Current status: $STATUS"

              if [ "$STATUS" = "completed" ]; then
                echo "Workflow completed with conclusion: $CONCLUSION"
                echo "GITHUB_WORKFLOW_RESULT=$CONCLUSION" >> $BASH_ENV
                break
              fi

              sleep 30
            done

            if [ "$STATUS" != "completed" ]; then
              echo "Workflow did not complete within 15 minutes"
              echo "GITHUB_WORKFLOW_RESULT=timed_out" >> $BASH_ENV
            fi

            echo "Continuing pipeline regardless of GitHub workflow outcome"
  write-docker-tag:
    parameters:
      environment:
        type: string
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "docker_tag = \"$(git rev-parse --short HEAD)\"" >> terraform/config_<< parameters.environment >>.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - terraform/

  fmt-validate-terraform:
    executor: terraform
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: .
      - terraform/init:
          path: terraform/
          backend_config_file: backends/<< parameters.environment >>.tfbackend
      - terraform/fmt:
          path: terraform/
      - terraform/validate:
          path: terraform/

  plan-terraform:
    executor: terraform
    environment:
      TF_CLI_ARGS: "-lock=false"
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: .
      - terraform/init:
          path: terraform/
          backend_config_file: backends/<< parameters.environment >>.tfbackend
      - terraform/plan:
          path: terraform/
          backend_config_file: backends/<< parameters.environment >>.tfbackend
          var_file: config_<< parameters.environment >>.tfvars

  apply-terraform:
    executor: terraform
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - run:
          name: Add curl
          command: apk --no-cache add curl jq
      - attach_workspace:
          at: .
      - terraform/init:
          path: terraform/
          backend_config_file: backends/<< parameters.environment >>.tfbackend
      - terraform/apply:
          path: terraform/
          backend_config_file: backends/<< parameters.environment >>.tfbackend
          var_file: config_<< parameters.environment >>.tfvars
          lock-timeout: 5m
      - slack/notify:
          channel: deployments
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: deployments
          event: pass
          template: basic_success_1

  ruby-checks:
    docker:
      - image: "cimg/ruby:3.4.2-node"
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Rubocop all files
          when: always
          command: |
            bundle exec rubocop
      - run:
          name: Inspecting with Brakeman
          when: always
          # See https://github.com/presidentbeef/brakeman/issues/1664
          command: "bundle exec brakeman -o test-results/brakeman/brakeman.junit -o brakeman.html --no-progress --separate-models"

  pre-commit:
    executor: python-executor
    steps:
      - tariff/pre-commit:
          terraform_version: 1.9.8

  test:
    docker:
      - image: cimg/ruby:3.4.2-node
        environment:
          BUNDLE_JOBS: "3"
          BUNDLE_RETRY: "3"
          RAILS_ENV: test
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/tariff_test"
          NODE_OPTIONS: --openssl-legacy-provider
      - image: cimg/postgres:13.11
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: tariff_test
          POSTGRES_PASSWORD: postgres
      - image: cimg/redis:5.0.14
    steps:
      - checkout
      - run:
          name: Install ruby dependencies
          command: |
            bundle install
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "Setup DB"
          command: |
            RAILS_ENV=test bundle exec rails db:migrate --trace
      - ruby/rspec-test
      - store_artifacts:
          path: coverage

  notify-production-deployment:
    docker:
      - image: cimg/ruby:3.4.2
    steps:
      - checkout

workflows:
  version: 2

  deploy-to-development:
    jobs:
      - ruby-checks:
          <<: *filter-not-main

      - pre-commit:
          <<: *filter-not-main

      - test:
          <<: *filter-not-main

      - write-docker-tag:
          name: write-docker-tag-dev
          environment: development
          <<: *filter-not-main

      - fmt-validate-terraform:
          name: fmt-terraform-dev
          context: trade-tariff-terraform-aws-development
          environment: development
          <<: *filter-not-main

      - plan-terraform:
          name: plan-terraform-dev
          context: trade-tariff-terraform-aws-development
          environment: development
          requires:
            - write-docker-tag-dev
            - fmt-terraform-dev
          <<: *filter-not-main

      - tariff/build-and-push:
          name: build-and-push-dev
          context: trade-tariff-terraform-aws-development
          environment: development
          image_name: tariff-admin
          ssm_parameter: "/development/ADMIN_ECR_URL"
          <<: *filter-not-main

      - apply-terraform:
          name: apply-terraform-dev
          context: trade-tariff-terraform-aws-development
          environment: development
          requires:
            - build-and-push-dev
            - ruby-checks
            - test
            - write-docker-tag-dev
          <<: *filter-not-main

      - trigger-github-e2e-tests:
          name: trigger-e2e-tests-dev
          test_url: https://dev.trade-tariff.service.gov.uk
          context: trade-tariff-terraform-aws-development
          requires:
            - apply-terraform-dev
          <<: *filter-not-main

      - tariff/smoketests:
          name: smoketest_dev
          context: trade-tariff-testing
          url: https://dev.trade-tariff.service.gov.uk
          yarn_run: dev-tariff-admin-smoketests
          requires:
            - apply-terraform-dev
          <<: *filter-not-main

  deploy-to-staging:
    jobs:
      - write-docker-tag:
          name: write-docker-tag-staging
          environment: staging

      - plan-terraform:
          name: plan-terraform-staging
          context: trade-tariff-terraform-aws-staging
          environment: staging
          requires:
            - write-docker-tag-staging
          <<: *filter-not-main

      - tariff/build-and-push:
          name: build-and-push-live
          context: trade-tariff-terraform-aws-staging
          environment: staging
          image_name: tariff-admin
          ssm_parameter: "/staging/ADMIN_ECR_URL"
          <<: *filter-main

      - apply-terraform:
          name: apply-terraform-staging
          context: trade-tariff-terraform-aws-staging
          environment: staging
          requires:
            - write-docker-tag-staging
            - plan-terraform-staging
            - build-and-push-live
          <<: *filter-main

      - trigger-github-e2e-tests:
          name: trigger-e2e-tests-staging
          test_url: https://staging.trade-tariff.service.gov.uk
          context: trade-tariff-terraform-aws-staging
          requires:
            - apply-terraform-staging
          <<: *filter-main

      - tariff/smoketests:
          name: smoketest_staging
          context: trade-tariff-testing
          url: https://staging.trade-tariff.service.gov.uk
          yarn_run: staging-tariff-admin-smoketests
          requires:
            - apply-terraform-staging
          <<: *filter-main

  deploy-to-production:
    jobs:
      - write-docker-tag:
          name: write-docker-tag-prod
          environment: production

      - plan-terraform:
          name: plan-terraform-prod
          context: trade-tariff-terraform-aws-production
          environment: production
          requires:
            - write-docker-tag-prod
          <<: *filter-not-main

      - promote-to-production?:
          type: approval
          <<: *filter-main

      - tariff/create-production-release:
          name: create-production-release
          context: trade-tariff-releases
          image-name: tariff-admin-production
          requires:
            - promote-to-production?
          <<: *filter-main

      - write-docker-tag:
          name: write-docker-tag-prod-release
          environment: production
          <<: *filter-release

      - apply-terraform:
          name: apply-terraform-prod
          context: trade-tariff-terraform-aws-production
          environment: production
          requires:
            - write-docker-tag-prod-release
          <<: *filter-release

      - notify-production-deployment:
          context: trade-tariff-releases
          requires:
            - apply-terraform-prod
          <<: *filter-release
