default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  host: <%= ENV['PGHOST'] %>
  user: <%= ENV.fetch("DB_USER", "postgres") %>
  database: tariff_admin_development

test:
  <<: *default
  host: <%= ENV.fetch('PGHOST', "localhost") %>
  user: <%= ENV.fetch("DB_USER", "postgres") %>
  database: tariff_admin_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>
