default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("DB_POOL", ENV.fetch("MAX_THREADS", 5)) %>

development:
  <<: *default
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  user: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV["PGPASSWORD"] %>
  database: tariff_admin_development

test:
  <<: *default
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  user: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV["PGPASSWORD"] %>
  database: tariff_admin_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
