default: &default
  encoding: utf8
  pool: 5

development:
  <<: *default
  adapter: sqlite3
  host: <%= ENV.fetch('PGHOST', 'localhost') %>
  user: <%= ENV.fetch("DB_USER", "postgres") %>
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  host: <%= ENV.fetch('PGHOST', "localhost") %>
  user: <%= ENV.fetch("DB_USER", "postgres") %>
  database: db/test.sqlite3

production:
  <<: *default
  <% if ENV['DATABASE_URL'].present? %>
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>
  <% else %>
  adapter: sqlite3
  database: db/production.sqlite3
  <% end %>
